// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datamodel.proto

package com.navneetgupta.bookstore.credit;

public final class Datamodel {
  private Datamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreditCardInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreditCardInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cardHolder = 1;</code>
     */
    java.lang.String getCardHolder();
    /**
     * <code>string cardHolder = 1;</code>
     */
    com.google.protobuf.ByteString
        getCardHolderBytes();

    /**
     * <code>string cardType = 2;</code>
     */
    java.lang.String getCardType();
    /**
     * <code>string cardType = 2;</code>
     */
    com.google.protobuf.ByteString
        getCardTypeBytes();

    /**
     * <code>string cardNumber = 3;</code>
     */
    java.lang.String getCardNumber();
    /**
     * <code>string cardNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getCardNumberBytes();

    /**
     * <code>int64 expiration = 4;</code>
     */
    long getExpiration();
  }
  /**
   * Protobuf type {@code CreditCardInfo}
   */
  public  static final class CreditCardInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CreditCardInfo)
      CreditCardInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreditCardInfo.newBuilder() to construct.
    private CreditCardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreditCardInfo() {
      cardHolder_ = "";
      cardType_ = "";
      cardNumber_ = "";
      expiration_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreditCardInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cardHolder_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cardType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              cardNumber_ = s;
              break;
            }
            case 32: {

              expiration_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.class, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder.class);
    }

    public static final int CARDHOLDER_FIELD_NUMBER = 1;
    private volatile java.lang.Object cardHolder_;
    /**
     * <code>string cardHolder = 1;</code>
     */
    public java.lang.String getCardHolder() {
      java.lang.Object ref = cardHolder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardHolder_ = s;
        return s;
      }
    }
    /**
     * <code>string cardHolder = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCardHolderBytes() {
      java.lang.Object ref = cardHolder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardHolder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object cardType_;
    /**
     * <code>string cardType = 2;</code>
     */
    public java.lang.String getCardType() {
      java.lang.Object ref = cardType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardType_ = s;
        return s;
      }
    }
    /**
     * <code>string cardType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCardTypeBytes() {
      java.lang.Object ref = cardType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDNUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object cardNumber_;
    /**
     * <code>string cardNumber = 3;</code>
     */
    public java.lang.String getCardNumber() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string cardNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCardNumberBytes() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRATION_FIELD_NUMBER = 4;
    private long expiration_;
    /**
     * <code>int64 expiration = 4;</code>
     */
    public long getExpiration() {
      return expiration_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCardHolderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cardHolder_);
      }
      if (!getCardTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cardType_);
      }
      if (!getCardNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cardNumber_);
      }
      if (expiration_ != 0L) {
        output.writeInt64(4, expiration_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCardHolderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cardHolder_);
      }
      if (!getCardTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cardType_);
      }
      if (!getCardNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cardNumber_);
      }
      if (expiration_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, expiration_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo)) {
        return super.equals(obj);
      }
      com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo other = (com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo) obj;

      boolean result = true;
      result = result && getCardHolder()
          .equals(other.getCardHolder());
      result = result && getCardType()
          .equals(other.getCardType());
      result = result && getCardNumber()
          .equals(other.getCardNumber());
      result = result && (getExpiration()
          == other.getExpiration());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CARDHOLDER_FIELD_NUMBER;
      hash = (53 * hash) + getCardHolder().hashCode();
      hash = (37 * hash) + CARDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCardType().hashCode();
      hash = (37 * hash) + CARDNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getCardNumber().hashCode();
      hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpiration());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreditCardInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreditCardInfo)
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.class, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder.class);
      }

      // Construct using com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cardHolder_ = "";

        cardType_ = "";

        cardNumber_ = "";

        expiration_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardInfo_descriptor;
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo getDefaultInstanceForType() {
        return com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance();
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo build() {
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo buildPartial() {
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo result = new com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo(this);
        result.cardHolder_ = cardHolder_;
        result.cardType_ = cardType_;
        result.cardNumber_ = cardNumber_;
        result.expiration_ = expiration_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo) {
          return mergeFrom((com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo other) {
        if (other == com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance()) return this;
        if (!other.getCardHolder().isEmpty()) {
          cardHolder_ = other.cardHolder_;
          onChanged();
        }
        if (!other.getCardType().isEmpty()) {
          cardType_ = other.cardType_;
          onChanged();
        }
        if (!other.getCardNumber().isEmpty()) {
          cardNumber_ = other.cardNumber_;
          onChanged();
        }
        if (other.getExpiration() != 0L) {
          setExpiration(other.getExpiration());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cardHolder_ = "";
      /**
       * <code>string cardHolder = 1;</code>
       */
      public java.lang.String getCardHolder() {
        java.lang.Object ref = cardHolder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cardHolder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cardHolder = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCardHolderBytes() {
        java.lang.Object ref = cardHolder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardHolder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cardHolder = 1;</code>
       */
      public Builder setCardHolder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cardHolder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cardHolder = 1;</code>
       */
      public Builder clearCardHolder() {
        
        cardHolder_ = getDefaultInstance().getCardHolder();
        onChanged();
        return this;
      }
      /**
       * <code>string cardHolder = 1;</code>
       */
      public Builder setCardHolderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cardHolder_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cardType_ = "";
      /**
       * <code>string cardType = 2;</code>
       */
      public java.lang.String getCardType() {
        java.lang.Object ref = cardType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cardType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cardType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCardTypeBytes() {
        java.lang.Object ref = cardType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cardType = 2;</code>
       */
      public Builder setCardType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cardType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cardType = 2;</code>
       */
      public Builder clearCardType() {
        
        cardType_ = getDefaultInstance().getCardType();
        onChanged();
        return this;
      }
      /**
       * <code>string cardType = 2;</code>
       */
      public Builder setCardTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cardType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cardNumber_ = "";
      /**
       * <code>string cardNumber = 3;</code>
       */
      public java.lang.String getCardNumber() {
        java.lang.Object ref = cardNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cardNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cardNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCardNumberBytes() {
        java.lang.Object ref = cardNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cardNumber = 3;</code>
       */
      public Builder setCardNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cardNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cardNumber = 3;</code>
       */
      public Builder clearCardNumber() {
        
        cardNumber_ = getDefaultInstance().getCardNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string cardNumber = 3;</code>
       */
      public Builder setCardNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cardNumber_ = value;
        onChanged();
        return this;
      }

      private long expiration_ ;
      /**
       * <code>int64 expiration = 4;</code>
       */
      public long getExpiration() {
        return expiration_;
      }
      /**
       * <code>int64 expiration = 4;</code>
       */
      public Builder setExpiration(long value) {
        
        expiration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expiration = 4;</code>
       */
      public Builder clearExpiration() {
        
        expiration_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CreditCardInfo)
    }

    // @@protoc_insertion_point(class_scope:CreditCardInfo)
    private static final com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo();
    }

    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreditCardInfo>
        PARSER = new com.google.protobuf.AbstractParser<CreditCardInfo>() {
      public CreditCardInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreditCardInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreditCardInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreditCardInfo> getParserForType() {
      return PARSER;
    }

    public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreditCardTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreditCardTransaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.CreditCardInfo cardInfo = 2;</code>
     */
    boolean hasCardInfo();
    /**
     * <code>.CreditCardInfo cardInfo = 2;</code>
     */
    com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo getCardInfo();
    /**
     * <code>.CreditCardInfo cardInfo = 2;</code>
     */
    com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfoOrBuilder getCardInfoOrBuilder();

    /**
     * <code>double amount = 3;</code>
     */
    double getAmount();

    /**
     * <code>string status = 4;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string confirmationCode = 5;</code>
     */
    java.lang.String getConfirmationCode();
    /**
     * <code>string confirmationCode = 5;</code>
     */
    com.google.protobuf.ByteString
        getConfirmationCodeBytes();

    /**
     * <code>int64 createTs = 6;</code>
     */
    long getCreateTs();
  }
  /**
   * Protobuf type {@code CreditCardTransaction}
   */
  public  static final class CreditCardTransaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CreditCardTransaction)
      CreditCardTransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreditCardTransaction.newBuilder() to construct.
    private CreditCardTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreditCardTransaction() {
      id_ = "";
      amount_ = 0D;
      status_ = "";
      confirmationCode_ = "";
      createTs_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreditCardTransaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder subBuilder = null;
              if (cardInfo_ != null) {
                subBuilder = cardInfo_.toBuilder();
              }
              cardInfo_ = input.readMessage(com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cardInfo_);
                cardInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              confirmationCode_ = s;
              break;
            }
            case 48: {

              createTs_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardTransaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.class, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDINFO_FIELD_NUMBER = 2;
    private com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo cardInfo_;
    /**
     * <code>.CreditCardInfo cardInfo = 2;</code>
     */
    public boolean hasCardInfo() {
      return cardInfo_ != null;
    }
    /**
     * <code>.CreditCardInfo cardInfo = 2;</code>
     */
    public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo getCardInfo() {
      return cardInfo_ == null ? com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance() : cardInfo_;
    }
    /**
     * <code>.CreditCardInfo cardInfo = 2;</code>
     */
    public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfoOrBuilder getCardInfoOrBuilder() {
      return getCardInfo();
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>double amount = 3;</code>
     */
    public double getAmount() {
      return amount_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 4;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIRMATIONCODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object confirmationCode_;
    /**
     * <code>string confirmationCode = 5;</code>
     */
    public java.lang.String getConfirmationCode() {
      java.lang.Object ref = confirmationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        confirmationCode_ = s;
        return s;
      }
    }
    /**
     * <code>string confirmationCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getConfirmationCodeBytes() {
      java.lang.Object ref = confirmationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        confirmationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETS_FIELD_NUMBER = 6;
    private long createTs_;
    /**
     * <code>int64 createTs = 6;</code>
     */
    public long getCreateTs() {
      return createTs_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (cardInfo_ != null) {
        output.writeMessage(2, getCardInfo());
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
      }
      if (!getConfirmationCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, confirmationCode_);
      }
      if (createTs_ != 0L) {
        output.writeInt64(6, createTs_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (cardInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCardInfo());
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
      }
      if (!getConfirmationCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, confirmationCode_);
      }
      if (createTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction)) {
        return super.equals(obj);
      }
      com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction other = (com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (hasCardInfo() == other.hasCardInfo());
      if (hasCardInfo()) {
        result = result && getCardInfo()
            .equals(other.getCardInfo());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getAmount())
          == java.lang.Double.doubleToLongBits(
              other.getAmount()));
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && getConfirmationCode()
          .equals(other.getConfirmationCode());
      result = result && (getCreateTs()
          == other.getCreateTs());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasCardInfo()) {
        hash = (37 * hash) + CARDINFO_FIELD_NUMBER;
        hash = (53 * hash) + getCardInfo().hashCode();
      }
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + CONFIRMATIONCODE_FIELD_NUMBER;
      hash = (53 * hash) + getConfirmationCode().hashCode();
      hash = (37 * hash) + CREATETS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreditCardTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreditCardTransaction)
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardTransaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardTransaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.class, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder.class);
      }

      // Construct using com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        if (cardInfoBuilder_ == null) {
          cardInfo_ = null;
        } else {
          cardInfo_ = null;
          cardInfoBuilder_ = null;
        }
        amount_ = 0D;

        status_ = "";

        confirmationCode_ = "";

        createTs_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditCardTransaction_descriptor;
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction getDefaultInstanceForType() {
        return com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance();
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction build() {
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction buildPartial() {
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction result = new com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction(this);
        result.id_ = id_;
        if (cardInfoBuilder_ == null) {
          result.cardInfo_ = cardInfo_;
        } else {
          result.cardInfo_ = cardInfoBuilder_.build();
        }
        result.amount_ = amount_;
        result.status_ = status_;
        result.confirmationCode_ = confirmationCode_;
        result.createTs_ = createTs_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction) {
          return mergeFrom((com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction other) {
        if (other == com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCardInfo()) {
          mergeCardInfo(other.getCardInfo());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getConfirmationCode().isEmpty()) {
          confirmationCode_ = other.confirmationCode_;
          onChanged();
        }
        if (other.getCreateTs() != 0L) {
          setCreateTs(other.getCreateTs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo cardInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfoOrBuilder> cardInfoBuilder_;
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public boolean hasCardInfo() {
        return cardInfoBuilder_ != null || cardInfo_ != null;
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo getCardInfo() {
        if (cardInfoBuilder_ == null) {
          return cardInfo_ == null ? com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance() : cardInfo_;
        } else {
          return cardInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder setCardInfo(com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo value) {
        if (cardInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cardInfo_ = value;
          onChanged();
        } else {
          cardInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder setCardInfo(
          com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder builderForValue) {
        if (cardInfoBuilder_ == null) {
          cardInfo_ = builderForValue.build();
          onChanged();
        } else {
          cardInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder mergeCardInfo(com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo value) {
        if (cardInfoBuilder_ == null) {
          if (cardInfo_ != null) {
            cardInfo_ =
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.newBuilder(cardInfo_).mergeFrom(value).buildPartial();
          } else {
            cardInfo_ = value;
          }
          onChanged();
        } else {
          cardInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder clearCardInfo() {
        if (cardInfoBuilder_ == null) {
          cardInfo_ = null;
          onChanged();
        } else {
          cardInfo_ = null;
          cardInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder getCardInfoBuilder() {
        
        onChanged();
        return getCardInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfoOrBuilder getCardInfoOrBuilder() {
        if (cardInfoBuilder_ != null) {
          return cardInfoBuilder_.getMessageOrBuilder();
        } else {
          return cardInfo_ == null ?
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance() : cardInfo_;
        }
      }
      /**
       * <code>.CreditCardInfo cardInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfoOrBuilder> 
          getCardInfoFieldBuilder() {
        if (cardInfoBuilder_ == null) {
          cardInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfo.Builder, com.navneetgupta.bookstore.credit.Datamodel.CreditCardInfoOrBuilder>(
                  getCardInfo(),
                  getParentForChildren(),
                  isClean());
          cardInfo_ = null;
        }
        return cardInfoBuilder_;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 4;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object confirmationCode_ = "";
      /**
       * <code>string confirmationCode = 5;</code>
       */
      public java.lang.String getConfirmationCode() {
        java.lang.Object ref = confirmationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          confirmationCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string confirmationCode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getConfirmationCodeBytes() {
        java.lang.Object ref = confirmationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          confirmationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string confirmationCode = 5;</code>
       */
      public Builder setConfirmationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        confirmationCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string confirmationCode = 5;</code>
       */
      public Builder clearConfirmationCode() {
        
        confirmationCode_ = getDefaultInstance().getConfirmationCode();
        onChanged();
        return this;
      }
      /**
       * <code>string confirmationCode = 5;</code>
       */
      public Builder setConfirmationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        confirmationCode_ = value;
        onChanged();
        return this;
      }

      private long createTs_ ;
      /**
       * <code>int64 createTs = 6;</code>
       */
      public long getCreateTs() {
        return createTs_;
      }
      /**
       * <code>int64 createTs = 6;</code>
       */
      public Builder setCreateTs(long value) {
        
        createTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createTs = 6;</code>
       */
      public Builder clearCreateTs() {
        
        createTs_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CreditCardTransaction)
    }

    // @@protoc_insertion_point(class_scope:CreditCardTransaction)
    private static final com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction();
    }

    public static com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreditCardTransaction>
        PARSER = new com.google.protobuf.AbstractParser<CreditCardTransaction>() {
      public CreditCardTransaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreditCardTransaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreditCardTransaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreditCardTransaction> getParserForType() {
      return PARSER;
    }

    public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreditTransactionCreatedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreditTransactionCreated)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CreditCardTransaction txn = 1;</code>
     */
    boolean hasTxn();
    /**
     * <code>.CreditCardTransaction txn = 1;</code>
     */
    com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction getTxn();
    /**
     * <code>.CreditCardTransaction txn = 1;</code>
     */
    com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder getTxnOrBuilder();
  }
  /**
   * Protobuf type {@code CreditTransactionCreated}
   */
  public  static final class CreditTransactionCreated extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CreditTransactionCreated)
      CreditTransactionCreatedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreditTransactionCreated.newBuilder() to construct.
    private CreditTransactionCreated(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreditTransactionCreated() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreditTransactionCreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder subBuilder = null;
              if (txn_ != null) {
                subBuilder = txn_.toBuilder();
              }
              txn_ = input.readMessage(com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(txn_);
                txn_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditTransactionCreated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditTransactionCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated.class, com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated.Builder.class);
    }

    public static final int TXN_FIELD_NUMBER = 1;
    private com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction txn_;
    /**
     * <code>.CreditCardTransaction txn = 1;</code>
     */
    public boolean hasTxn() {
      return txn_ != null;
    }
    /**
     * <code>.CreditCardTransaction txn = 1;</code>
     */
    public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction getTxn() {
      return txn_ == null ? com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance() : txn_;
    }
    /**
     * <code>.CreditCardTransaction txn = 1;</code>
     */
    public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder getTxnOrBuilder() {
      return getTxn();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (txn_ != null) {
        output.writeMessage(1, getTxn());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (txn_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTxn());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated)) {
        return super.equals(obj);
      }
      com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated other = (com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated) obj;

      boolean result = true;
      result = result && (hasTxn() == other.hasTxn());
      if (hasTxn()) {
        result = result && getTxn()
            .equals(other.getTxn());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTxn()) {
        hash = (37 * hash) + TXN_FIELD_NUMBER;
        hash = (53 * hash) + getTxn().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreditTransactionCreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreditTransactionCreated)
        com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditTransactionCreated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditTransactionCreated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated.class, com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated.Builder.class);
      }

      // Construct using com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (txnBuilder_ == null) {
          txn_ = null;
        } else {
          txn_ = null;
          txnBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navneetgupta.bookstore.credit.Datamodel.internal_static_CreditTransactionCreated_descriptor;
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated getDefaultInstanceForType() {
        return com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated.getDefaultInstance();
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated build() {
        com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated buildPartial() {
        com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated result = new com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated(this);
        if (txnBuilder_ == null) {
          result.txn_ = txn_;
        } else {
          result.txn_ = txnBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated) {
          return mergeFrom((com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated other) {
        if (other == com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated.getDefaultInstance()) return this;
        if (other.hasTxn()) {
          mergeTxn(other.getTxn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction txn_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder> txnBuilder_;
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public boolean hasTxn() {
        return txnBuilder_ != null || txn_ != null;
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction getTxn() {
        if (txnBuilder_ == null) {
          return txn_ == null ? com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance() : txn_;
        } else {
          return txnBuilder_.getMessage();
        }
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public Builder setTxn(com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction value) {
        if (txnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          txn_ = value;
          onChanged();
        } else {
          txnBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public Builder setTxn(
          com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder builderForValue) {
        if (txnBuilder_ == null) {
          txn_ = builderForValue.build();
          onChanged();
        } else {
          txnBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public Builder mergeTxn(com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction value) {
        if (txnBuilder_ == null) {
          if (txn_ != null) {
            txn_ =
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.newBuilder(txn_).mergeFrom(value).buildPartial();
          } else {
            txn_ = value;
          }
          onChanged();
        } else {
          txnBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public Builder clearTxn() {
        if (txnBuilder_ == null) {
          txn_ = null;
          onChanged();
        } else {
          txn_ = null;
          txnBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder getTxnBuilder() {
        
        onChanged();
        return getTxnFieldBuilder().getBuilder();
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      public com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder getTxnOrBuilder() {
        if (txnBuilder_ != null) {
          return txnBuilder_.getMessageOrBuilder();
        } else {
          return txn_ == null ?
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance() : txn_;
        }
      }
      /**
       * <code>.CreditCardTransaction txn = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder> 
          getTxnFieldBuilder() {
        if (txnBuilder_ == null) {
          txnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransaction.Builder, com.navneetgupta.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder>(
                  getTxn(),
                  getParentForChildren(),
                  isClean());
          txn_ = null;
        }
        return txnBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CreditTransactionCreated)
    }

    // @@protoc_insertion_point(class_scope:CreditTransactionCreated)
    private static final com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated();
    }

    public static com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreditTransactionCreated>
        PARSER = new com.google.protobuf.AbstractParser<CreditTransactionCreated>() {
      public CreditTransactionCreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreditTransactionCreated(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreditTransactionCreated> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreditTransactionCreated> getParserForType() {
      return PARSER;
    }

    public com.navneetgupta.bookstore.credit.Datamodel.CreditTransactionCreated getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreditCardInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreditCardInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreditCardTransaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreditCardTransaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreditTransactionCreated_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreditTransactionCreated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017datamodel.proto\"^\n\016CreditCardInfo\022\022\n\nc" +
      "ardHolder\030\001 \001(\t\022\020\n\010cardType\030\002 \001(\t\022\022\n\ncar" +
      "dNumber\030\003 \001(\t\022\022\n\nexpiration\030\004 \001(\003\"\222\001\n\025Cr" +
      "editCardTransaction\022\n\n\002id\030\001 \001(\t\022!\n\010cardI" +
      "nfo\030\002 \001(\0132\017.CreditCardInfo\022\016\n\006amount\030\003 \001" +
      "(\001\022\016\n\006status\030\004 \001(\t\022\030\n\020confirmationCode\030\005" +
      " \001(\t\022\020\n\010createTs\030\006 \001(\003\"?\n\030CreditTransact" +
      "ionCreated\022#\n\003txn\030\001 \001(\0132\026.CreditCardTran" +
      "sactionB0\n!com.navneetgupta.bookstore.cr" +
      "editB\tDatamodelH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CreditCardInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreditCardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreditCardInfo_descriptor,
        new java.lang.String[] { "CardHolder", "CardType", "CardNumber", "Expiration", });
    internal_static_CreditCardTransaction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreditCardTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreditCardTransaction_descriptor,
        new java.lang.String[] { "Id", "CardInfo", "Amount", "Status", "ConfirmationCode", "CreateTs", });
    internal_static_CreditTransactionCreated_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreditTransactionCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreditTransactionCreated_descriptor,
        new java.lang.String[] { "Txn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
